create extension if not exists pgcrypto;

create table if not exists public.pandals (
  id uuid primary key default gen_random_uuid(), name text not null, zone text not null,
  address text, latitude double precision not null, longitude double precision not null,
  verified boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.crowd_updates (
  id bigint generated by default as identity primary key,
  pandal_id uuid not null references public.pandals(id) on delete cascade,
  level text not null check(level in('low','medium','high')), queue_minutes integer,
  source text not null, reported_at timestamptz not null, expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(), name text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  invite_code text not null unique,
  expires_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id uuid references public.groups(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  can_share_location boolean not null default false, joined_at timestamptz not null default now(),
  primary key(group_id,user_id)
);
create table if not exists public.photo_posts (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  image_path text not null, caption text, status text not null default 'pending' check(status in('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.pandals enable row level security; alter table public.crowd_updates enable row level security;
alter table public.groups enable row level security; alter table public.group_members enable row level security; alter table public.photo_posts enable row level security;

create policy "verified pandals are public" on public.pandals for select to anon,authenticated using(verified=true);
create policy "active crowd is public" on public.crowd_updates for select to anon,authenticated using(expires_at>now());
create policy "users create groups" on public.groups for insert to authenticated with check(created_by=auth.uid());
create policy "members read groups" on public.groups for select to authenticated using(created_by=auth.uid() or exists(select 1 from public.group_members gm where gm.group_id=groups.id and gm.user_id=auth.uid()));
create policy "users add themselves" on public.group_members for insert to authenticated with check(user_id=auth.uid());
create policy "members read membership" on public.group_members for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.group_members gm2 where gm2.group_id=group_members.group_id and gm2.user_id=auth.uid()));
create policy "user can create own photo post" on public.photo_posts for insert to authenticated with check(user_id=auth.uid());
create policy "approved photos are public" on public.photo_posts for select to anon,authenticated using(status='approved' or user_id=auth.uid());
create policy "user can update own photo" on public.photo_posts for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create policy "group members receive broadcasts" on realtime.messages for select to authenticated using(
  extension in('broadcast','presence') and exists(select 1 from public.group_members gm where gm.user_id=auth.uid() and ('group:'||gm.group_id::text)=realtime.topic())
);
create policy "group members send broadcasts" on realtime.messages for insert to authenticated with check(
  extension='broadcast' and exists(select 1 from public.group_members gm where gm.user_id=auth.uid() and ('group:'||gm.group_id::text)=realtime.topic())
);
